### ISSUE TITLE
Errors on 1.16.4 - Please update

### ISSUE THREAD

**Issue by brandcrystal** [FesterHead/Quests#11]
1.16.4 isn't registering block break or place events, causing issues all around the board. Please update!

**Comment by kingvonx** [comment]
Hmmmmm i will try hahaha but i 'm not good in coding so i will try only

**Comment by brandcrystal** [comment]
Eagerly waiting for an update

**Comment by ImHumbug** [comment]
rip

**Comment by FesterHead** [comment]
@brandcrystal - see https://github.com/FesterHead/Quests/releases/tag/3.4.4
@ImHumbug - diaf
